### ISSUE TITLE
Can't commit a large obj file

### ISSUE THREAD

**Issue by CheahHsunTeik** [fenix-hub/godot-engine.github-integration#38] opened 2020-05-09 07:01 UTC
I've created a 100 by 100 by 4 model in blender and export it as obj into Godot, but now when I want to commit it to GitHub, it keeps loading forever...

![Screenshot (137)](https://user-images.githubusercontent.com/33892130/81466657-e2748400-9205-11ea-985a-0e72564aa678.png)

Committing my other obj files works though, only this particular obj doesn't work...
Godot version:3.2stable
Plugin version: I've just downloaded/cloned it from GitHub

**Comment by CheahHsunTeik** [comment] 2020-05-09 07:24
Not sure whether it's related, but sometimes I can't even choose the branch I wanna commit to...
![image](https://user-images.githubusercontent.com/33892130/81467116-100efc80-9209-11ea-98cf-5b03fb7d8670.png)
![image](https://user-images.githubusercontent.com/33892130/81467123-17cea100-9209-11ea-8460-265709cf3ec4.png)

**Comment by fenix-hub** [comment] 2020-05-09 09:01
Hi @CheahHsunTeik ,

Regarding the first issue, I'm pretty sure that it may be caused by the file size.
I still don't have the time to setup git-LFS for the plugin, so large files may cause a crash for the upload. Without LFS, the standard limit of 100MB size per file will be respected with this plugin (which is something Github does automatically if you try to upload the file by yourself).
If the file is <100MB, the issue may be linked to the extension itself.
Please, update me on the file size and if you can share with me the file so I can do some tests.

If the second issue happens after the first, it is caused by internal errors of the plugin.
A reload of the plugin should work fine, anyway I'll investigate more.

**Comment by CheahHsunTeik** [comment] 2020-05-09 10:15
File Size: 40.2MB

I can't send the file since GitHub doesn't support the file type, so here's the link:
https://gofile.io/d/Ju9Aiv

I don't think it is because of the extension, cause other files with the same extension works...
For now, what can I do to commit the file?

**Comment by fenix-hub** [comment] 2020-05-09 15:57
As soon as I'm able too I'll invastigate.
If you are not able to commit this file even via browser or command line I think there is something wrong with the file itself.

**Comment by CheahHsunTeik** [comment] 2020-05-09 16:18
Ok,I'll try to commit it with the command line and let u know the result...
I can't commit with the browser cause the file size limit for browser is 25MB...

**Comment by CheahHsunTeik** [comment] 2020-05-10 02:15
Update:I've tried committing the file using github desktop and it works...

**Comment by fenix-hub** [comment] 2020-05-11 23:01
Hi,
sorry if I kept you waiting.
So, I checked the error with your .obj file. Actually it is not neither a plugin error or a file problem, but it is actually a engine problem.
I'm not really sure what the problem is about, but it may be linked to size of the content (which I take as a String, and may be over the maximum byte size).
I'll post this issue directly to Godot Engine's repository, so I'll get some help to make this work also for you.

Regarding this issue:
> Not sure whether it's related, but sometimes I can't even choose the branch I wanna commit to...
> ![image](https://user-images.githubusercontent.com/33892130/81467116-100efc80-9209-11ea-98cf-5b03fb7d8670.png)
> ![image](https://user-images.githubusercontent.com/33892130/81467123-17cea100-9209-11ea-8460-265709cf3ec4.png)
please, I'd like to have some more informations about it.
Some steps to reproduce it, if it happens randomly or with specific repositories, or after a specific operation (commit, editing, deleting files, ecc.)

Thank you.

**Comment by CheahHsunTeik** [comment] 2020-05-13 09:26
I'm not really sure how to reproduce it,it just happens when I'm trying to commit a file.
Probable causes:
1)Trying to commit the large new water.obj file.
2)I have deleted the log file prior to the error,but most probably it is not the cause.
I can't think of anything that I have done differently that resulted in that error.

Actually I've just started to use this plugin for less than a day before I encountered the problems,so idk much about it..sorry...

**Comment by fenix-hub** [comment] 2020-05-15 08:50
Hi, as you can see I opened an issue on the official repository. You can follow that issue if you want, as soon as I'll get help I'll update you.

For the second issue, I still don't know how to reproduce it. Tried to do some specific tasks and some commits but everything seems to work both for me and all users.
If it happens again, please remember to take a screenshot of the output, or of the external output if you happen to use it.
To activate it, `Editor/EditorSettings/Editor` and untick `Hide Console Window`, then restart the project or the whole Engine.

I'll close this issue, but if you encounter any problem please contact me or open a new issue.
Also, I'm releasing a soft update with some minor bug fixes and utilities.

**Closed as completed by fenix-hub** 2020-05-15 08:50 UTC
